# Set baseURL in environment configs

languageCode = "de-de"
DefaultContentLanguage = "de"
title = "Mordheim Regelwerk"
theme = "ace-documentation"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window


[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
    unsafe = true