name: Hugo
  
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Hugo site

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
          image: ext-alpine
          env: production