name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
          image: ext-alpine